version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: build.Dockerfile
    container_name: airport-management-api
    environment:
      - SERVER_PORT=8080
      - DB_USERNAME=prokopchuk
      - DB_PASSWORD=localdb
      - DB_URL=jdbc:postgresql://airport-management-db:5432/airport-management-db
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    container_name: airport-management-db
    environment:
      - POSTGRES_USER=prokopchuk
      - POSTGRES_DB=airport-management-db
      - POSTGRES_PASSWORD=localdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: localdb
    ports:
      - "5050:80"

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-db
      DB_DATABASE: airport-management-db
      DB_USER: prokopchuk
      DB_PASSWORD: localdb
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "9090:8080"
    depends_on:
      - postgres-db
    links:
      - postgres-db

volumes:
  db-data:
    driver: local