spring:
  datasource:
    username: ${DB_USERNAME:localdb}
    password: ${DB_PASSWORD:localdb}
    url: ${DB_URL:jdbc:postgresql://localhost:5432}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: db/changelog-master.xml
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/auth/realms/airport-management-system

jwt:
  auth:
    converter:
      resource-id: ams-auth
      principal-attribute: preferred_username