name: Java CI with Maven and JaCoCo test coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        cd ./airport-management-backend
        ./mvnw -B package --file pom.xml
      
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.3
      with:
        paths: ${{ github.workspace }}/airport-management-backend/target/site/jacoco/jacoco.xml
        token: ${{ secrets.REPO_COMMIT_TOKEN }}
        min-coverage-overall: 50
        min-coverage-changed-files: 10
        
    - name: Log coverage percentage
      run: |
        echo "coverage overall = ${{ steps.jacoco.outputs.coverage-overall }}"
        echo "coverage changed files = ${{ steps.jacoco.outputs.coverage-changed-files }}"

    - name: Update dependency graph
      run: cd ./airport-management-backend
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
